### ISSUE TITLE
Use /pod API instead of /endpoint for the default configuration

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#112]
Currently, while using Kubernetes Discovery Strategy with no parameters and no service defined, the members do not discover themselves. The reason for that is that we use `/endpoint` Kubernetes API which returns only PODs related to services. We should change it to `/pod` and if no properties are defined, then discover all PODs in the namespace.

**Comment by CassieAin** [comment]
I think it should be mentioned in the Readme somehow. Because right now there is such an information:

> Note: If you don't specify any property at all, then the Hazelcast cluster is formed using all PODs in your current namespace. In other words, you can look at the properties as a grouping feature if you want to have multiple Hazelcast clusters in one namespace.
