### ISSUE TITLE
Hazelcast instance used for 2nd Hibernate cache cannot connect stably in Kubernetes

### ISSUE THREAD

**Issue by futurexv2016** [hazelcast/hazelcast-kubernetes#124]
hi, I have an issue when using embedded Hazelcast deployed in Kubernetes(GKE) to enable 2nd level cache Hibernate in Spring Boot application. Spingboot app connect to Spanner by using spanner-jdbc (https://github.com/olavloite/spanner-jdbc). I deploy 1 service (replicas=2) to k8s, however hazelcast instances located in 2 pods cannot connect stably (it works when server starts but then seem disconnected after, please the below log). This causes 2nd level cache cannot be shared between 2 pods.
pom.xml
![selection_012](https://user-images.githubusercontent.com/19494537/50703118-b2ebbf80-1085-11e9-967b-bbb6a049872b.png)

Springboot Application.java:
![selection_007](https://user-images.githubusercontent.com/19494537/50702127-9ef28e80-1082-11e9-8d18-52b19f9fce4d.png)

deployment.yaml:
![selection_008](https://user-images.githubusercontent.com/19494537/50702212-cfd2c380-1082-11e9-8ba9-fd871babf579.png)

Spanner Datasource file:
![selection_009](https://user-images.githubusercontent.com/19494537/50702250-ee38bf00-1082-11e9-9bcf-b5e653210f2a.png)

Application.properties
![selection_010](https://user-images.githubusercontent.com/19494537/50702284-0c062400-1083-11e9-889a-25efa09352a8.png)

Pod logs:
Pod1: 
![selection_004](https://user-images.githubusercontent.com/19494537/50702311-2809c580-1083-11e9-8a1e-426576a27b1e.png)
Pod2:
![selection_005](https://user-images.githubusercontent.com/19494537/50702330-30620080-1083-11e9-9e61-6278ea313748.png)

One outstanding log is: Config seed port is 5701 and cluster size is 1. Some of the ports seem occupied!

As you see, the second log has only 1 member whereas the first has 2 members. I tested by issuing rest request to service which then distributed to each pods, the test result is sometimes cache are shared between two pods, sometimes not.
I expected 2nd Hibernate cache should be shared between 2 pods in the service
Anyone here can help this situation? Thank you very much.

**Comment by leszko** [comment]
Please follow the same discussion on StackOverlflow: https://stackoverflow.com/questions/54037219/hazelcast-instance-used-for-2nd-hibernate-cache-cannot-connect-stably-in-kuberne

**Comment by futurexv2016** [comment]
Thanks, the issue is resolved according to the answer in the link.
