### ISSUE TITLE
Remove deprecated properties

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#129]
The following properties are deprecated and should be removed in the next release:
- `service-port`
- `service-label-name`
- `service-label-value`

**Comment by henrikarro** [comment]
I'm currently using `service-label-name` and `service-label-value` to mark the "service-per-pod" services that are used by the Hazelcast clients outside the Kubernetes cluster to connect to Hazelcast.

Is there another way of doing this without using these properties?

**Comment by leszko** [comment]
@henrikarro Thanks for the comment.
At the same time we plan to introduce this: https://github.com/hazelcast/hazelcast-kubernetes/issues/115

Would this solve your issue if you label all the pods for your cluster? 
If not, please describe your use case scenario. We may still consider keeping these parameters.

Actually the reason I'd like to have them removed is that they're confusing. People label their Pods and wonder why the auto-discovery does not work. Anyway, your input is important. 

Thanks!

**Comment by leszko** [comment]
Closing (as discussed in #115).
