### ISSUE TITLE
Couldn't connect to the Kubernetes master

### ISSUE THREAD

**Issue by fireplace009** [hazelcast/hazelcast-kubernetes#132]
Hello,
I'm trying to get my hazelcast working in openshift.
But I'm receiving **_Couldn't connect to the Kubernetes master_**

- I added the dependencies

> <dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-kubernetes</artifactId>
			<version>1.4</version>

- added in the hazelcast config in my project.

> 			<multicast enabled="false" /><kubernetes enabled="true"/>

- configured a service account in openshift (admin role)

Am I forgetting something? (or more probably misunderstanding it?)

> 2019-03-26 12:58:41.747  INFO 7 --- [           main] c.h.s.d.integration.DiscoveryService     : [100.126.151.213]:5701 [dev] [3.11] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-port: 0, service-label: null, service-label-value: true, namespace: myproject, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc }
  | 2019-03-26 12:58:41.845  INFO 7 --- [           main] c.h.s.d.integration.DiscoveryService     : [100.126.151.213]:5701 [dev] [3.11] Kubernetes Discovery activated resolver: KubernetesApiEndpointResolver
  | 2019-03-26 12:58:42.689  INFO 7 --- [           main] com.hazelcast.instance.Node              : [100.126.151.213]:5701 [dev] [3.11] Activating Discovery SPI Joiner
  | 2019-03-26 12:58:46.545  INFO 7 --- [           main] c.h.s.i.o.impl.OperationExecutorImpl     : [100.126.151.213]:5701 [dev] [3.11] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
  | 2019-03-26 12:58:46.646  INFO 7 --- [           main] c.h.internal.diagnostics.Diagnostics     : [100.126.151.213]:5701 [dev] [3.11] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2019-03-26 12:58:46.742  INFO 7 --- [           main] com.hazelcast.core.LifecycleService      : [100.126.151.213]:5701 [dev] [3.11] [100.126.151.213]:5701 is STARTING
  | 2019-03-26 12:58:50.350  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [1] retrying in 1 seconds...
  | 2019-03-26 12:58:51.949  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [2] retrying in 2 seconds...
  | 2019-03-26 12:58:54.248  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [3] retrying in 3 seconds...
  | 2019-03-26 12:58:57.644  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [4] retrying in 5 seconds...
  | 2019-03-26 12:59:02.737  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [5] retrying in 7 seconds...
  | 2019-03-26 12:59:10.350  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [6] retrying in 11 seconds...
  | 2019-03-26 12:59:21.778  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [7] retrying in 17 seconds...
  | 2019-03-26 12:59:38.934  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [8] retrying in 25 seconds...
  | 2019-03-26 13:00:04.622  WARN 7 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [9] retrying in 38 seconds...

**Comment by leszko** [comment]
@fireplace009 
1. After 10 retries, you should see the exact stacktrace, could you share it?
2. Could you share the project and the exact steps to reproduce?

**Comment by fireplace009** [comment]
Hey Leszko, 
Thank for the quick reply/

As you can see, after the 10 tries, he does create a cluster. 
Running a second pod however does not make them find each other. 
They just both create their own single node cluster.

The rest of the stack:

> 2019-03-26 14:24:34.216  WARN 8 --- [           main] com.hazelcast.kubernetes.RetryUtils      : Couldn't connect to the Kubernetes master, [10] retrying in 57 seconds...
  | 2019-03-26 14:25:31.907  WARN 8 --- [           main] c.h.s.d.integration.DiscoveryService     : [100.126.149.78]:5701 [dev] [3.11] Cannot fetch the current zone, ZONE_AWARE feature is disabled
  | 2019-03-26 14:25:32.406  WARN 8 --- [           main] c.hazelcast.kubernetes.KubernetesClient  : Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
  | 2019-03-26 14:25:32.612  INFO 8 --- [cached.thread-2] com.hazelcast.nio.tcp.TcpIpConnector     : [100.126.149.78]:5701 [dev] [3.11] Connecting to /100.126.151.213:9001, timeout: 0, bind-any: true
  | 2019-03-26 14:25:32.810  INFO 8 --- [.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection    : [100.126.149.78]:5701 [dev] [3.11] Connection[id=1, /100.126.149.78:45471->/100.126.151.213:9001, endpoint=[100.126.151.213]:9001, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
  | 2019-03-26 14:25:33.513  INFO 8 --- [cached.thread-7] com.hazelcast.nio.tcp.TcpIpConnector     : [100.126.149.78]:5701 [dev] [3.11] Connecting to /100.126.151.213:9001, timeout: 0, bind-any: true
  | 2019-03-26 14:25:33.521  INFO 8 --- [.IO.thread-in-1] com.hazelcast.nio.tcp.TcpIpConnection    : [100.126.149.78]:5701 [dev] [3.11] Connection[id=2, /100.126.149.78:56176->/100.126.151.213:9001, endpoint=[100.126.151.213]:9001, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
  | 2019-03-26 14:25:34.515  INFO 8 --- [cached.thread-7] com.hazelcast.nio.tcp.TcpIpConnector     : [100.126.149.78]:5701 [dev] [3.11] Connecting to /100.126.151.213:9001, timeout: 0, bind-any: true
  | 2019-03-26 14:25:34.527  INFO 8 --- [.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection    : [100.126.149.78]:5701 [dev] [3.11] Connection[id=3, /100.126.149.78:37717->/100.126.151.213:9001, endpoint=[100.126.151.213]:9001, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
  | 2019-03-26 14:25:35.514  INFO 8 --- [cached.thread-7] com.hazelcast.nio.tcp.TcpIpConnector     : [100.126.149.78]:5701 [dev] [3.11] Connecting to /100.126.151.213:9001, timeout: 0, bind-any: true
  | 2019-03-26 14:25:35.518  INFO 8 --- [.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection    : [100.126.149.78]:5701 [dev] [3.11] Connection[id=4, /100.126.149.78:51358->/100.126.151.213:9001, endpoint=[100.126.151.213]:9001, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
  | 2019-03-26 14:25:36.515  INFO 8 --- [cached.thread-7] com.hazelcast.nio.tcp.TcpIpConnector     : [100.126.149.78]:5701 [dev] [3.11] Connecting to /100.126.151.213:9001, timeout: 0, bind-any: true
  | 2019-03-26 14:25:36.521  INFO 8 --- [.IO.thread-in-1] com.hazelcast.nio.tcp.TcpIpConnection    : [100.126.149.78]:5701 [dev] [3.11] Connection[id=5, /100.126.149.78:59107->/100.126.151.213:9001, endpoint=[100.126.151.213]:9001, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled
  | 2019-03-26 14:25:37.515  INFO 8 --- [           main] c.h.internal.cluster.ClusterService      : [100.126.149.78]:5701 [dev] [3.11]
  | Members {size:1, ver:1} [
  | Member [100.126.149.78]:5701 - 8e8ad01b-0101-438b-9255-0a47c2873181 this
  | ]
  | 2019-03-26 14:25:37.619  INFO 8 --- [           main] com.hazelcast.core.LifecycleService      : [100.126.149.78]:5701 [dev] [3.11] [100.126.149.78]:5701 is STARTED


the hazelconfig:

> <network>
		<join>
			<multicast enabled="false" />
			<kubernetes enabled="true">
				<service-name>watchdogs</service-name>
				<service-port>9001</service-port>
				<namespace>co-pilot-qa</namespace>
			</kubernetes>
		</join>
	

Sharing the project unfortunately won't be possible

**Comment by leszko** [comment]
`<service-port>9001</service-port>` this looks suspicious. You need to expose Hazelcast port (5701) in the service if you want to use `service-port`.

**Comment by fireplace009** [comment]
Ok, YES !
Thank you :)

modified the service port to 

> <service-port>5701</service-port>

Members {size:2, ver:2} [
--
  | Member [100.126.149.78]:5701 - 8e8ad01b-0101-438b-9255-0a47c2873181
  | Member [100.126.145.235]:5701 - 3f560fdf-3fc9-462a-bc21-0efc18a6a29a this
  | ]


Why is he complaining about the kubernetes-master ?

**Comment by leszko** [comment]
Good point. I've changed the error message here: #133 . Closing this one. Feel free to reopen if you still encounter any issues.
