### ISSUE TITLE
More granular RBAC permissions?

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast-kubernetes#138]
Can you please provide the specific rules besides the generically broad set covered under the `view` role per the README.

For example, granting the entire `view` role seems pretty broad for a hazelcast app in k8

What specific `resources` and corresponding `verbs` does hazelcast actually need to do the discovery?

**Comment by bitsofinfo** [comment]
i.e is it just `pods` and `endpoints`?

**Comment by mesutcelik** [comment]
Yes it is. We also only assign `get` and `list` verbs.
You can see the minimum list in the official helm chart repository.
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/role.yaml#L15
