### ISSUE TITLE
Where is 1.5 published?

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast-kubernetes#140]
I can't pull this in gradle

```
    compile group: "com.hazelcast", name: "hazelcast-kubernetes", version: "1.5"
    
    
```

**Comment by leszko** [comment]
We'll publish 1.5 on Wednesday. Currently if you look at the [releases](https://github.com/hazelcast/hazelcast-kubernetes/releases), it's in the "Pre-release" state. Hope it helps. 

Closing this one. Feel free to reopen if needed.
