### ISSUE TITLE
Lite-members for Helm

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-kubernetes#144]
The Helm chart only creates non-lite members.

It would be useful if it could create lite-members also.

**Comment by leszko** [comment]
Helm Chart is only about creating the Hazelcast cluster, not really the client. What would be the usage of the lite member in that case?

**Comment by neilstevenson** [comment]
Lite-members are part of the cluster, they are not clients, and can be promoted to full members.
Since they are cluster members, we should be able to create them with a helm chart

**Comment by leszko** [comment]
Moved to https://github.com/hazelcast/charts/issues/39
