### ISSUE TITLE
Helm chart using Yaml

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-kubernetes#145]
The Helm chart should be able to use `hazelcast.yaml` 

Given the Yaml name of Helm, this could be the default

**Comment by leszko** [comment]
Helm Chart uses YAML. Please see: https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L32

**Comment by mesutcelik** [comment]
That is the PR for central repo update
https://github.com/helm/charts/pull/13474
