### ISSUE TITLE
Makes sense to use default resolve-not-ready-addresses true?

### ISSUE THREAD

**Issue by crashodd** [hazelcast/hazelcast-kubernetes#153]
Some time ago we were migrating all our services to kubernetes and we face some problems with the applications that were making use of hazelcast.

Some of this applications while booting up are loading some static data meant to be hosted in hazelcast, but applied some logic to only masters in hz cluster would do the logic and only would be loaded once.

Once moved to k8s we were expecting to have the same behaviour in kubernetes, autodiscover themselves at the beginning without even getting the ok from readiness, but started experiencing delay in all the applications, since all the pods were doing this heavy load. Once we discovered this property 

> resolve-not-ready-addresses

everything came back to normal. So here comes our proposal. Does it make sense to set this property 

> https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java#L81

with default value true to make it consistent with non kubernetes hazelcast implementation (for us it does :D )?

Regards

**Comment by leszko** [comment]
@crashodd , it makes sense to me. It's a non-backward compatible change, but we can merge into the `4.0-compatibility` branch and then release together with Hazelcast 4.0.

**Comment by crashodd** [comment]
Awesome!

Thank you very much for the quick response!

Keep it up guys!!!

**Comment by leszko** [comment]
Fixed by #172
