### ISSUE TITLE
Outside Kubernetes Cluster : unknown properties use-public-ip, ca-certificate

### ISSUE THREAD

**Issue by yyoussouf** [hazelcast/hazelcast-kubernetes#189]
Hi,

I tried to follow your instructions to connect to a hazelcast server installed on kubernetes from a client outside of it.
The server works, I can connect inside the kubernetes cluster.
When I configure the java client which is outside kubernetes with this configuration inspired by  the readme file (I tried with xml configuration and programmatically in java, both failed the same way) : 
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.11.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>
    <network>
        <discovery-strategies>
            <discovery-strategy enabled="true"
                                class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                <properties>
                    <property name="service-name">SVC</property>
                    <property name="namespace">NS</property>
                    <property name="use-public-ip">true</property>
                    <property name="kubernetes-master">KUBE_MASTER</property>
                    <property name="api-token">TOKEN</property>
                    <property name="ca-certificate">CERT</property>
                </properties>
            </discovery-strategy>
        </discovery-strategies>
    </network>
</hazelcast-client>
```

I get the error : 

> Exception in thread "main" java.lang.RuntimeException: Failed to configure discovery strategies
> 	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:149)
> 	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:57)
> 	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
> 	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.initDiscoveryService(HazelcastClientInstanceImpl.java:456)
> 	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:252)
> 	at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
> 	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
> 	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
> 	at com.accor.distrib.irma.distributed.HazelcastClientTest.main(HazelcastClientTest.java:50)
> Caused by: com.hazelcast.config.InvalidConfigurationException: Unknown properties: '[use-public-ip, ca-certificate]' on discovery strategy
> 	at com.hazelcast.spi.discovery.impl.DiscoveryServicePropertiesUtil.verifyNoUnknownProperties(DiscoveryServicePropertiesUtil.java:88)

I saw in the class HazelcastKubernetesDiscoveryStrategyFactory that those unrecognized properties are missing in the collection of properties definitions, is that normal?

Regards

**Comment by leszko** [comment]
@yyoussouf , which hazelcast version do you use for the client? `hazelcast-all:3.12.5`?

You can also try following this code sample: https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client

**Comment by yyoussouf** [comment]
I checked my dependencies version after reading your comment and it was my hazelcast-kubernetes version  which was bad, thanks a lot
