### ISSUE TITLE
DNS Lookup: namespaces ?

### ISSUE THREAD

**Issue by fireplace009** [hazelcast/hazelcast-kubernetes#194]
I was wondering if it were possible to add namespaces to the configuration when working with dns lookup.

Situation:
I have two pods, working correctly.
When I wish to deploy a new version (rolling deployment), it will sync the new pods with the old pods and keeping the cache. However in this specific situation (new version) I would like the cache to be version specific, so the old pods work with the old cache (untill they are shut down by kubernetes) and the new pods works with a new cache

I was thinking by using a namespace (filled in by maven plugin with the version)
That way forcing this behavior.

Or is there a better way?

Kind regards,
B;

**Comment by leszko** [comment]
@fireplace009 thanks for asking the question!

I'm not sure I understand correctly, especially this part.

> However in this specific situation (new version) I would like the cache to be version specific, so the old pods work with the old cache (untill they are shut down by kubernetes) and the new pods works with a new cache

If your PODs formed one cluster then they share all the data, so there is no "new cache" and "old cache". Could you clarify?

Wrt namespaces, you can specify the namespace, it's in the service-dns name: `SERVICE-NAME.NAMESPACE.svc.cluster.local`

**Comment by fireplace009** [comment]
Hey Leszko,
the service-dns name we use to make sure the pods find each other. that works perfectly.

I guess I'm asking if within the same cluster, there can be versions of the cache?
Where a pod is linked only to a specific version of that cache?


if you don't understand my usecase ... I'll try to explain it
Use-case
Deploying version 1 of our spring-boot application
Configure 2 pods. -> cache is shared: All is peachy !

Then after some new additions/features to the code,... we wish to deploy this new version (version 2) of our spring-boot application.

Rolling Deployment: 
- (version 1) 2 pods // (version 2) 1 pod -> version2 pod gets the cache of version1
- (version 1) 1 pods // (version 2) 2 pods
- (version 1) 0 pods // (version 2) 2 pods

But I want different behavior:
Because of the fact that the new pod is serving a newer version, I want it to be 'disconnected' from the 'old version clustered cache', and start a 'new version clustered cache'


hope that makes sense?

**Comment by leszko** [comment]
I see, I think I understand now. So you'd like start new version of your application with a new and fresh cache and not connect to the old one. 

I think you cannot change it at the level of the discovery, but what you probably can do is to set up the [cluster-name](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml#L73) parameter each time to a different value. Then, they should form separate clusters.

**Comment by fireplace009** [comment]
Awesome ! that's what I was looking for.
Thanks for helping out.
