### ISSUE TITLE
Warning log entries about ZONE_AWARE and cannot fetch public IPs

### ISSUE THREAD

**Issue by ChangSurrey** [hazelcast/hazelcast-kubernetes#196]
I'm using v1.5.2 of the plugin with hazelcast v3.12.6.

I'm using the following settings in hazelcast.xml:
```
         <network>
            <join>
                <multicast enabled="false" />
                <tcp-ip enabled="false" />
                <kubernetes enabled="true">
                    <namespace>my_namespace</namespace>
                    <service-name>hazelcast-primary</service-name>
                    <resolve-not-ready-addresses>true</resolve-not-ready-addresses>
                </kubernetes>
            </join>
            <rest-api enabled="true">
                <endpoint-group name="HEALTH_CHECK" enabled="true"/>
            </rest-api>
        </network>
```

It's working fine for me, and the hazelcast cluster forms correctly. 
However, I'm confused by the following 2 warning lines in the log.

```
2020-02-26 15:16:18.827|WARN|main||[172.100.55.217]:5701 [dev] [3.12.6] Cannot fetch the current zone, ZONE_AWARE feature is disabled|com.hazelcast.spi.discovery.integration.DiscoveryService
2020-02-26 15:16:19.042|WARN|main||Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network|com.hazelcast.kubernetes.KubernetesClient
```

I'm not exposing hazelcast outside the k8s cluster - the `hazelcast-primary` service is used internally only. 

In this case, do I need to worry about these logs? If yes, how do I fix them?

**Comment by mesutcelik** [comment]
No worries about those. They indicate that your kubernetes cluster nodes are not labeled with `failure-domain.kubernetes.io/zone` and your pods do not have public IPs.

I guess those can be converted into INFO. cc: @leszko

**Comment by ChangSurrey** [comment]
Ok thanks for clarifying.

**Comment by leszko** [comment]
Yeah, I think we can concert to `INFO`. Actually, we should read in `hazelcast-kubernetes` if ZONE_AWARE is enabled and print this log only if that's the case.
