### ISSUE TITLE
Treat empty string properties as null

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#197]
When empty string is passed as a property, it should be treated as null, not as a correct value.

The change should be implemented in [KubernetesConfig](https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java).

Related to https://github.com/hazelcast/charts/issues/58

**Comment by jawitcher** [comment]
Hi. Can I work on this issue?

**Comment by leszko** [comment]
@jawitcher Sure, it's yours!

**Comment by jawitcher** [comment]
@leszko, could you check my PR https://github.com/hazelcast/hazelcast-kubernetes/pull/201?

**Comment by leszko** [comment]
@jawitcher , you've sent it as DRAFT, is it ready to review?

**Comment by jawitcher** [comment]
@leszko , yes, it is. I don't know if I understand the issue correctly, That's why I've send the pr as draft

**Comment by leszko** [comment]
@jawitcher Thanks! Added my comments in the related PR.

**Comment by leszko** [comment]
Fixed by #201
