### ISSUE TITLE
An issue with split-brain error on Kubernetes

### ISSUE THREAD

**Issue by alimalek71** [hazelcast/hazelcast-kubernetes#200]
Hi,

I am using `spring boot 2.2.6.RELEASE` with `embedded` Hazelcast cache in `Kubernetes`.
I use `service-dns` for discovery strategy but I have a problem with the split-brain error.
I deploy my app with exactly 2 replicas, instances of my app start and each embedded Hazelcast works independently. 

I set split-brain property `hazelcast.merge.first.run.delay.seconds=0`, in both pods logs there is a log that determines they know there is another instance and they should be merge together but they failed to merge.

If I start with one pod and after that, scale to more than one pod, there is no error and the pods make a cluster without any problem. The problem comes when 2 pods start immediately. 

The Error is:
```15:35.543 [hz.c7d3cc81-4671-44f8-b1a7-f5d7b29d8331.priority-generic-operation.thread-0] INFO  c.h.i.c.i.o.SplitBrainMergeValidationOp - [10.40.0.12]:5701 [K8S] [3.12.6] Removing null, since it thinks it's already split from this cluster and looking to merge.
23:15:35.544 [hz.c7d3cc81-4671-44f8-b1a7-f5d7b29d8331.priority-generic-operation.thread-0] ERROR c.h.i.c.i.o.SplitBrainMergeValidationOp - [10.40.0.12]:5701 [K8S] [3.12.6] Target is this node! -> [10.40.0.12]:5701
java.lang.IllegalArgumentException: Target is this node! -> [10.40.0.12]:5701
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.checkTarget(OutboundResponseHandler.java:219)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendNormalResponse(OutboundResponseHandler.java:123)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:86)
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:456)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:412)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
23:15:35.545 [hz.c7d3cc81-4671-44f8-b1a7-f5d7b29d8331.priority-generic-operation.thread-0] WARN  c.h.s.i.o.impl.OperationRunnerImpl - [10.40.0.12]:5701 [K8S] [3.12.6] While sending op error... op: com.hazelcast.internal.cluster.impl.operations.SplitBrainMergeValidationOp{serviceName='hz:core:clusterService', identityHash=257578366, partitionId=-1, replicaIndex=0, callId=4, invocationTime=1586198735541 (2020-04-06 23:15:35.541), waitTimeout=-1, callTimeout=60000}, error: java.lang.IllegalArgumentException: Target is this node! -> [10.40.0.12]:5701
```

What I missed in the configuration could you help me?

**Comment by mesutcelik** [comment]
Hmm.. Maybe `hazelcast.merge.first.run.delay.seconds=0` is too low as it is run only startup time.
`hazelcast.merge.first.run.delay.seconds` can be given a higher value like a few seconds based on your environment. 

`hazelcast.merge.next.run.delay.seconds` is another parameter you can experiment in case future split-brain detections.

Descriptions of paratemeters are listed here.
https://docs.hazelcast.org/docs/latest/manual/html-single/

**Comment by mesutcelik** [comment]
One optimization that can be here is to introduce a [retry](https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java#L92) mechanism for SRV records. 

@leszko What do you think?

**Comment by alimalek71** [comment]
Thanks for fast replay :pray: 

I set it `0`, to start to find split-brain as soon a possible.
And by default, the other value is `120 seconds` which means 2 minutes, but now after 40 minutes, these instances couldn't merge together.

**Comment by mesutcelik** [comment]
That is not normal. Can you create a reproducer and share with us?

**Comment by alimalek71** [comment]
I will create a git repo and share a sample code plus my k8s configs.

**Comment by leszko** [comment]
@alimalek71 I guess the problem is that both Pods start at the same time and headless service does not have the DNS configured yet. 

To solve it, we [recommend](https://github.com/hazelcast/hazelcast-kubernetes#requirements-and-recommendations):
- using StatefulSet (then Pods do not start at the same time) or
- using [Kubernetes API](https://github.com/hazelcast/hazelcast-kubernetes#kubernetes-api) discovery

---------------------------

> I set it `0`, to start to find split-brain as soon a possible.
> And by default, the other value is `120 seconds` which means 2 minutes, but now after 40 minutes, these instances couldn't merge together.

With regards to why instances do not merge... that is weird to be honest. Normally, they should merge in around 2 min. 40 min sound wrong.

**Comment by alimalek71** [comment]
> @alimalek71 I guess the problem is that both Pods start at the same time and headless service does not have the DNS configured yet.

@leszko Yes exactly like you said it happens.

I will test both options.

**Comment by mesutcelik** [comment]
@alimalek71 Have you had a chance to look at it?

**Comment by alimalek71** [comment]
> @alimalek71 Have you had a chance to look at it?

I apologize for the delay in replying.

Yes with changing to StatefulSet type the problem solved.
