### ISSUE TITLE
Improve permission configuration experience

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-kubernetes#209]
I deployed a docker image to my GKS and I am getting this:
```
SEVERE: Kubernetes API forbidden access, please check that your Service Account have the correct (Cluster) Role rules
Jun 12, 2020 10:56:17 AM com.hazelcast.kubernetes.KubernetesClient
SEVERE: Kubernetes API forbidden access, please check that your Service Account have the correct (Cluster) Role rules
Jun 12, 2020 10:56:18 AM com.hazelcast.kubernetes.KubernetesClient
SEVERE: Kubernetes API forbidden access, please check that your Service Account have the correct (Cluster) Role rules
Jun 12, 2020 10:56:18 AM com.hazelcast.internal.cluster.ClusterService
```

At this point I have to:
1. Go to IMDG reference manual: https://docs.hazelcast.org/docs/4.0.1/manual/html-single/index.html#kubernetes-cloud-discovery
2. Click at the link taking you to https://github.com/hazelcast/hazelcast-kubernetes
3. Find the section about permission configuration
4. Copy and paste the snippet and create a local file
5. `kubectl apply -f ./permissions.yaml`

Improvements I foresee:
1. The error message should provide more guidance. 
2. We could expose the permission file so as a user I could do just `kubectl apply https://some-url` without copy-n-pasting. 

#2 could be included in the error message. I realize sometimes you want to customize the file, but I suspect most of new users will just use the default. 

One consideration: If we expose an URL with the permission yaml then this URL will effectivelly become API and we should treat it as such.

**Comment by leszko** [comment]
Sent a PR on that. It's hard to make it generic, but at least I've created something that works for `default` service account, for `default` namespace.
