### ISSUE TITLE
Improve diagnosic logging for RestClientException

### ISSUE THREAD

**Issue by kennymacleod** [hazelcast/hazelcast-kubernetes#217]
`RestClientException` is thrown by `RestClient` and caught and logged by `KubernetesClient`. While the exception message contains vital information such as the requested URI, this is only logged by `KubernetesClient` at `trace` level, which is never going to be enabled on anything resembling a production system. Otherwise, the only logging is a generic message about "auth failure" or "forbidden", with no informaton about the URI.

`KubernetesClient` could be easily tweaked to include the exception message at normal logging levels.

**Comment by leszko** [comment]
@kennymacleod Would you like to send a PR with that change?

**Comment by kennymacleod** [comment]
@leszko done!

**Comment by leszko** [comment]
Thanks! I'll review it soon.
