### ISSUE TITLE
Namespace is not read from serviceaccount/namespace as per docs

### ISSUE THREAD

**Issue by kennymacleod** [hazelcast/hazelcast-kubernetes#219]
In the project docs, the config property `namespace` is documented thus:

> namespace: Kubernetes Namespace where Hazelcast is running; if not specified, the value is taken from the environment variables KUBERNETES_NAMESPACE or OPENSHIFT_BUILD_NAMESPACE. If those are not set, the namespace of the POD will be used (retrieved from /var/run/secrets/kubernetes.io/serviceaccount/namespace).

However, this isn't what actually happens. If none of the property or the environment variables mentioned are set, the namespace defaults to `default`. It never attempts to read from the `serviceaccount/namespace` file.

**Comment by leszko** [comment]
I think the current version works correctly and we decided to not backport it since the change is not backwards-compatible. Please check #183.

**Comment by kennymacleod** [comment]
You're quite right, it's already fixed on main branch. This does mean tha the documentation is only correct for the main branch, but that's a minor issue.

**Comment by leszko** [comment]
yeah, the documentation is for the current version. You can check the old doc under the tags. For example, here: https://github.com/hazelcast/hazelcast-kubernetes/tree/v1.5.4
