### ISSUE TITLE
Q: Given scenario of changing replicas from 0 to 2+ ... members join/discover each other later than desired

### ISSUE THREAD

**Issue by rbygrave** [hazelcast/hazelcast-kubernetes#24]
Hi,
Thanks for the plugin, it is working really well.

One scenario I have noticed is that when there are no running pods with Hazelcast and we try to start with replicas of 2 or more (jump from 0 to 2+ replicas).  In this scenario the initial `discovery` does not find any currently running pods to join and so the 2 replicas start without joining each other.

At some point later they join/discover each other.  So it seems (and makes sense) that Hazelcast triggers/polls the discovery plugin periodically to find new nodes etc.

Now in our use case we are using a replicated map and we need to be careful to avoid this scenario (going from 0 pods to many pods) as the replicated maps are not in sync just at the point of pod startup and that is a problem for our use case. The replicated maps do come into sync at some point later (I believe Hazelcast polls the discovery plugin later and the nodes join and sync).

I wonder if others have looked at this and got other thoughts.

Cheers, Rob.

**Comment by philnate** [comment]
I didn't notice any issue with the replica. Our cluster is configured right from the start to have 3 replicas and all nodes find each other. But the issue I stumple upon is that if I define a readinessProbe the nodes won't find each other, or if used with min cluster size hazelcast doesn't even startup correctly.

I didn't yet see that they eventually join, maybe the time waited was just to short for me.

**Comment by rbygrave** [comment]
We have readinessProbe and livenessProbe configured (on all our services).  Those don't seem to be a problem for our Hazelcast setup.  Note that our pods are very slow to start (~60 seconds) so when we have no running instances and start 3 pods concurrently all of them are able to ask kube (at initial discovery time) and not know about the 'other 2 pods that are currently starting' and to me that seems pretty valid as they might yet fail to start etc (so they only discover the other pods later on).  I can reproduce this issue at will on our clusters (but it might be related to the slow startup time).

If there is 1 pod already running then I have not seen any "discovery" problem.

A caveat here is that with our replicatedMap if we had `<async-fillup>false</async-fillup>` we had problems bringing up nodes (perhaps some race condition with discovery and replicated map fillup - not sure) but we are using `<async-fillup>true</async-fillup>` and doing a `get` against the map in @PostConfigured (late startup phase) to ensure our replicated map is populated before our pod instance is up - and that is working well to date.

**Comment by noctarius** [comment]
Hey sorry for the late response. There are a few practical properties to optimize discovery and startup in cloud environments.

`hazelcast.initial.min.cluster.size`: If you have a minimum number of nodes in the cluster, let the cluster itself wait on startup until the minimum number of nodes is reached.
`hazelcast.merge.first.run.delay.seconds`: The seconds before the initial try to "merge" independent clusters or not yet discovered nodes. Set this to to like 15-20 seconds should speed up forming the cluster.
`hazelcast.merge.next.run.delay.seconds`: The seconds between individual merge runs. Default is 120 secs and that's about ok as only first nodes have an issue (normally).

Those properties are all described in the docs: http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#system-properties

In 3.8 though another useful bit comes into play. There's a new minimalistic healthcheck REST endpoint which can be enabled using `hazelcast.http.healthcheck.enabled` set to `true`. The merged PR can be found [here](https://github.com/hazelcast/hazelcast/pull/9284) and the simple healthcheck script for my openshift image is over [here](https://github.com/noctarius/hazelcast-docker/blob/openshift-rhel/hazelcast-openshift/healthcheck.sh).

**Comment by philnate** [comment]
Just realizing that likely my readiness probe and the consideration what is healthy is faulty.
I have Spring Boot HealthIndicator for Hazelcast returning simply up/down depending on the return value of `HazelcastInstance.getLifecycleService().isRunning()`. @rbygrave how do you determine if the node is healthy?

**Comment by noctarius** [comment]
You could use `HazelcastInstance::getPartitionService::isClusterSafe`, that is what I do in the new code for the healthcheck (+ some more additional information).

**Comment by rbygrave** [comment]
@philnate Our readiness probe doesn't check Hazelcast yet.  

`HazelcastInstance::getPartitionService::isClusterSafe` ... I'm going to have a look at this - thanks @noctarius 

Side Issue: We have twice had (not reproducible at this stage) nodes in the cluster start throwing `CallerNotMemberException: Not Member` after deployment - https://groups.google.com/forum/#!topic/hazelcast/_M_ezca4M0E  ... `getPartitionService::isClusterSafe` might help us with that.

**Comment by googlielmo** [comment]
The original question was answered, it seems. Closing this.
