### ISSUE TITLE
Verify CP Subsystem usage on Kubernetes

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#262]

**Comment by leszko** [comment]
I checked and currently, Hazelcast CP Subsystem does not work correctly in Kubernetes. This is because the assumption of CP Subsystem is that the Hazelcast cluster is stable (stable IP addresses) and if any member is restarted it should be manually removed from the cluster as described in [Hazelcast Reference Manual: CP Subsystem’s Fault Tolerance Capabilities](https://docs.hazelcast.org/docs/latest/manual/html-single/#cp-subsystems-fault-tolerance-capabilities). In Kubernetes however, restarting PODs is an automatic (and expected) operation.

I tested what happens with the enabled CP Subsystem when the rolling upgrade is performed. The member fails with the [following logs](https://github.com/hazelcast/hazelcast-kubernetes/files/5750291/logs.txt) and CP Sybsystem Group never recovers.

**Comment by sancar** [comment]
Hi Rafal, Did you enable CP Persistence as I suggested here to the user https://github.com/hazelcast/hazelcast/issues/15299#issuecomment-726591461 ?

**Comment by leszko** [comment]
I tried it now, and actually, yes, it solves the issue. I updated the doc here: https://github.com/hazelcast/hazelcast-kubernetes/pull/289

Additionally, we need to support it in the Helm Chart, created an issue here: https://github.com/hazelcast/charts/issues/176
