### ISSUE TITLE
Add `topology.kubernetes.io/zone`

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#267]
`failure-domain.beta.kubernetes.io/zone` is deprecated, we need to use `topology.kubernetes.io/zone` instead.

https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

**Comment by bbuyukormeci** [comment]
- label "failure-domain.beta.kubernetes.io/zone" should be maintained to grant backward compatibility with Kubernetes < 1.17 (and consequently Openshift < 4.4 )
- label "failure-domain.kubernetes.io/zone" should be replaced by the label "topology.kubernetes.io/zone" to grant compliancy with Kubernetes >= 1.17 (and consequently Openshift 4.4+)

**Comment by leszko** [comment]
Yeah, I think to be backward-compatible we'll keep `failure-domain.beta.kubernetes.io/zone` (and probably also `failure-domain.kubernetes.io/zone`, because we've seen some clusters using it).
