### ISSUE TITLE
Hazelcast Kubernetes tries to access serviceaccount-token even if DNS Lookup is chosen method

### ISSUE THREAD

**Issue by fr1zle** [hazelcast/hazelcast-kubernetes#284]
https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java#L45

On this line the Kubernetes API Client is constructed, even if DNS_LOOKUP is chosen as discovery strategy.
This results in an attempt to access `/var/run/secrets/kubernetes.io/serviceaccount/token` which while fail in environments where token does not get auto-mounted for security reasons.

**Comment by hasancelik** [comment]
Hi @fr1zle,

Thanks for reporting. you are right, if DNS_LOOKUP is enabled, the token does not require. The plugin needs to handle edge cases like above. 

Do you want to create PR for it?

**Comment by fr1zle** [comment]
Sure, I can give it a try.
