### ISSUE TITLE
Typo in sample code: incorrect class name

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast-kubernetes#35]
I just want to report a typo on the main Github page of this plugin that caused me some headaches getting this plugin working.

In the DNS Lookup section of README.adoc, the discovery-strategy class name is incorrectly set to _com.hazelcast.HazelcastKubernetesDiscoveryStrategy_, where it should be set to _com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy_ instead.

Hazelcast doesn't throw any Exceptions or logs any errors whatsoever, which makes this error extremely annoying to realize.

**Comment by lazerion** [comment]
@fschuh Thanks, document is updated.
