### ISSUE TITLE
Hazelcast port not configurable

### ISSUE THREAD

**Issue by opoto** [hazelcast/hazelcast-kubernetes#40]
When using the DnsEndpointResolver, the Hazelcast port cannot be configured: the DnsEndpointResolver.getHazelcastPort() method always returns the static DEFAULT_PORT value. Could this port value be configurable, just as it is when using the ServiceEndpointResolver?

**Comment by noctarius** [comment]
The REST API offers the port information coming from the service definition, whereas the data from kubernetes DNS do not include this information. The only way I'd see it happening would make a property to pass in which can override the default in case of DNS.

**Comment by opoto** [comment]
Yes, it would be great to add eg KubernetesProperties.SERVICE_PORT, and use it as default in DnsEndpointResolver.getHazelcastPort().

**Comment by xqianwang** [comment]
I have a question, what are endpoint additional properties (endpointAddress.getAdditionalProperties)

**Comment by googlielmo** [comment]
Fixed by #60
