### ISSUE TITLE
How to connect a client to a cluster

### ISSUE THREAD

**Issue by Sutty100** [hazelcast/hazelcast-kubernetes#41]
I have setup my cluster using the service-name option which works fine and multiple hazelcast nodes discover each other. However I can't figure out how to get my clients (spring boot java apps) to connect to all members in the cluster other than by specifying ip address which obviously does not fit with the K8 model. Can somebody advice/add to the docs how to connect a client that is running in the same K8 cluster?

**Comment by cesartl** [comment]
I'm new to this but I'm hoping to try something like that:
```xml
<hazelcast-client>
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>
    <network>
        <!-- activate the Kubernetes plugin -->
        <discovery-strategies>
            <discovery-strategy enabled="true"
                                class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">

                <properties>
                    <!-- configure discovery service API lookup -->
                    <property name="service-name">${hazelcast.service.name}</property>
                    <property name="namespace">${k8sNAMESPACE}</property>
                </properties>
            </discovery-strategy>
        </discovery-strategies>
    </network>
</hazelcast-client>
```

**Comment by googlielmo** [comment]
Hi @Sutty100 I'm going to close this issue as the question was answered.
We will update the documentation and/or code samples for this case.
Thanks for contributing!
Cheers,
Guglielmo
