### ISSUE TITLE
Instruction doesn't applied for Hazelcast 3.9.1

### ISSUE THREAD

**Issue by senwangrockets** [hazelcast/hazelcast-kubernetes#59]
For the Hazelcast 3.9.1

I've tried with with configuration

```
<!-- activate the Kubernetes plugin -->
      <discovery-strategies>
        <discovery-strategy enabled="true"
            class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">

          <properties>
            <!-- configure discovery service API lookup -->
            <property name="service-name">MY-SERVICE-NAME</property>
             <property name="service-label-name">cluster01</property>
              <property name="service-label-value">true</property>
            <property name="namespace">MY-KUBERNETES-NAMESPACE</property>
          </properties>
        </discovery-strategy>
      </discovery-strategies>
```
But I then encounter an error shown as below:

```
Caused by: com.hazelcast.config.properties.ValidationException: There is no discovery strategy factory to create 'DiscoveryStrategyConfig{properties={namespace=default}, className='com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy', discoveryStrategyFactory=null}' Is it a typo in a strategy classname? Perhaps you forgot to include implementation on a classpath?
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:188)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:145)
```

**Comment by senwangrockets** [comment]
Instead, if I use java code

`JoinConfig joinConfig = cfg.getNetworkConfig().getJoin();
    joinConfig.getMulticastConfig().setEnabled(false);
    DiscoveryConfig discoveryConfig = joinConfig.getDiscoveryConfig();

    DiscoveryStrategyFactory factory = new HazelcastKubernetesDiscoveryStrategyFactory();
    DiscoveryStrategyConfig strategyConfig = new DiscoveryStrategyConfig(factory);

    discoveryConfig.addDiscoveryStrategyConfig(strategyConfig);

    HazelcastMapConfigDecorator.getInstance().setupMapConfig(cfg);`

to configure hazelcast, then it works. But I haven't figured out a way to make it work with XML format.

**Comment by mesutcelik** [comment]
Hi,

Can you please add this parameter as well?
```
<properties>
    <property name="hazelcast.discovery.enabled">true</property>
  </properties>
```

https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-enterprise-kubernetes/hazelcast.xml#L23

**Comment by senwangrockets** [comment]
No, I still cannot make it work by use xml
I tried 
`<?xml version="1.0" encoding="UTF-8"?>
<hazelcast
    xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.9.xsd"
    xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>

    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>

    <map name="default">
        <backup-count>1</backup-count>
        <in-memory-format>BINARY</in-memory-format>
        <time-to-live-seconds>60</time-to-live-seconds>
        <max-idle-seconds>60</max-idle-seconds>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="PER_NODE">5000</max-size>
    </map>

    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="false" />
            <discovery-strategies>
                <discovery-strategy enabled="true"
                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                    <properties>
                        <property name="namespace">default</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>

</hazelcast>`

and `<?xml version="1.0" encoding="UTF-8"?>
<hazelcast
        xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.9.xsd"
        xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <group>
                <name>dev</name>
                <password>dev-pass</password>
        </group>

        <properties>
                <property name="hazelcast.discovery.enabled">true</property>
        </properties>

        <map name="default">
                <backup-count>1</backup-count>
                <in-memory-format>BINARY</in-memory-format>
                <time-to-live-seconds>60</time-to-live-seconds>
                <max-idle-seconds>60</max-idle-seconds>
                <eviction-policy>LRU</eviction-policy>
                <max-size policy="PER_NODE">5000</max-size>
        </map>

        <network>
                <port auto-increment="true" port-count="100">5701</port>
                <outbound-ports>
                        <ports>0</ports>
                </outbound-ports>
                <join>
                        <multicast enabled="false" />
                        <tcp-ip enabled="false" />
                        <discovery-strategies>
                                <discovery-strategy enabled="true"
                                        class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactory">
                                        <properties>
                                                <property name="namespace">default</property>
                                        </properties>
                                </discovery-strategy>
                        </discovery-strategies>
                </join>
        </network>

</hazelcast>`

But none of them works.

I encounter error message,
`Dec 11, 2017 3:50:39 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.1] Prefer IPv4 stack is true.
Dec 11, 2017 3:50:50 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.1] Picked [172.16.32.15]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Dec 11, 2017 3:50:50 PM com.hazelcast.system
INFO: [172.16.32.15]:5701 [dev] [3.9.1] Hazelcast 3.9.1 (20171130 - feca534) starting at [172.16.32.15]:5701
Dec 11, 2017 3:50:50 PM com.hazelcast.system
INFO: [172.16.32.15]:5701 [dev] [3.9.1] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Dec 11, 2017 3:50:50 PM com.hazelcast.system
INFO: [172.16.32.15]:5701 [dev] [3.9.1] Configured Hazelcast Serialization version: 1
Dec 11, 2017 3:50:54 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.16.32.15]:5701 [dev] [3.9.1] Backpressure is disabled
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: Invalid configuration
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:151)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
        at com.hazelcast.instance.Node.createDiscoveryService(Node.java:265)
        at com.hazelcast.instance.Node.<init>(Node.java:216)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:160)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:128)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at com.genband.util.hazelcastserver.HazelcastServer.main(HazelcastServer.java:24)
Caused by: com.hazelcast.config.properties.ValidationException: There is no discovery strategy factory to create 'DiscoveryStrategyConfig{properties={namespace=default}, className='com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy', discoveryStrategyFactory=null}' Is it a typo in a strategy classname? Perhaps you forgot to include implementation on a classpath?
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:188)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:145)
        ... 11 more`

**Comment by googlielmo** [comment]
Hi @senwangrockets 
I assume you are using a custom Docker image with Hazelcast 3.9.1, is this the case?
What version of the `hazelcast-kubernetes` plugin are you using? Is it 1.0.0 or just the latest from master?
The exception actually looks like a classpath issue, are you using the same image for both cases, with and without xml configuration?

**Comment by senwangrockets** [comment]
@googlielmo Yes, I'm currently using a custom docker image with hazelcast-kubernetes 1.0.0. I did use the same image for both cases. The java code configuration works fine, hazelcast server clustered together without any problem. I'm use maven-shade-plugin to package my jars.

**Comment by googlielmo** [comment]
@senwangrockets The usage of `maven-shade-plugin` looks suspicious to me.
When you use Java code the `HazelcastKubernetesDiscoveryStrategyFactory` class will be loaded correctly, independently of shading (because the plugin will take care of it).
But when you use the xml file, the class will be instantiated *by name*, so it will not be found precisely because of the shading (it will be in a different package).
Could you please share the configuration for the shade plugin that you're using?

Cheers,
Guglielmo

**Comment by senwangrockets** [comment]
Thanks @googlielmo, I think it is a good point, I will test with updated configuration at my earliest convenience.

**Comment by googlielmo** [comment]
Hi @senwangrockets, did your test go well? Can we close this issue?

**Comment by googlielmo** [comment]
On the assumption that the suggestion above fixes the issue, I'm closing this. Feel free to reopen if needed.
