### ISSUE TITLE
Integration with kubernetes horizontal pod autoscaling

### ISSUE THREAD

**Issue by arthurdm** [hazelcast/hazelcast-kubernetes#62]
This is a feature request to integrate Hazelcast with Kubernete's [horizontal pod autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) (HPA).  

The newer `autoscaling/v2beta1` version of HPA allows for memory and custom metrics to be used instead of CPU utilization, however, some experiments with this API illustrated that HZ pods could scale up but did not scale down (i.e. they did not trigger a scale down threshold).

This feature request is for an investigation, design and implementation on how to best integrate HZ's metrics with kubernetes such that both scaling up and down occurs.

**Comment by dacleyra** [comment]
The novel idea is to use Kubernetes auto-scaling functionality to scale out the Hazelcast data grid when it nears capacity, or to scale it in once evictions have shrunk the grid to a certain threshold.

Kubernetes memory based auto-scaling reads the RSS of the of the container. In testing a hazelcast-wm client scenario with a remote grid, the HZ container RSS doesn't seem to shrink when sessions have expired and should be evicted. Ultimately keying scaling off of RSS for JVMs is tricky in the first place.

The better general fit would be scaling based on heap memory, or the specific fit of grid capacity statistic. This would involve using the Kubernetes Custom Metric option for autoscaling.


A current methodology for consuming custom metrics by autoscaling is

- Deploy a metrics collector (Prometheus)
- Configure metrics collector to scrape from (http/https) endpoint of pod(s), /metrics
  - MicroProfile conforms to this https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/metrics_spec.adoc
- Deploy the metrics adapter
  - For Prometheus https://github.com/directxman12/k8s-prometheus-adapter


Options in mind


- Option 1.
  - Implement a metrics adapter specifically for surfacing relevant HZ metrics
    - https://github.com/kubernetes/metrics
- Option 2.
  - Implement a metrics endpoint that can be scraped to be used in conjunction with a metrics collector

**Comment by dacleyra** [comment]
The current thought is to propose including the Prometheus JMX exporter javaagent in the hazelcast-kubernetes docker image.
https://github.com/prometheus/jmx_exporter

This would export Hazelcast's JMX metics on an endpoint which could be scraped by Prometheus, and fed into autoscaling.

**Comment by mesutcelik** [comment]
Thanks @dacleyra , your contribution would be appreciated once you test your integration.

**Comment by leszko** [comment]
@dacleyra , the JMX metrics Prometheus agent is already [included in the Hazelcast Docker image](https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-oss/jmx_agent_config.yaml).

Also, @mesutcelik recently wrote a [blog post about Hazelcast Horizontal Pod Autoscaling](https://hazelcast.com/blog/autoscaling-with-horizontal-pod-autoscaler/).

Do you think we can close this issue now?

**Comment by dacleyra** [comment]
Yes, it can be closed, thank you.
