### ISSUE TITLE
SocketException[Connection refused to address /172.16.60.55:5701]

### ISSUE THREAD

**Issue by ummershervani** [hazelcast/hazelcast-kubernetes#65]
Hello, I am having issues while trying to have hazelcast connecting to other nodes.  Let me know if I am missing anything. I would assume that if should find other nodes and auto connect to it. 

Here is my k8 deployment:

NAME:   hazelcast
REVISION: 1
RELEASED: Wed Feb 28 13:46:56 2018
CHART: hazelcast-testhz-0.1.0
USER-SUPPLIED VALUES:
env:
  gitCommit: f34wew2a5aer33ffas7a
  springProfile: qa
image:
  pullPolicy: Always
  repository: hazelcast/hazelcast-kubernetes
  tag: 3.10-BETA-1
ingress:
  enabled: true
  hosts:
  - hazelcast.us-west-2.nonprod.cnqr.delivery
  tls:
  - hosts:
    - hazelcast.us-west-2.nonprod.cnqr.delivery
nginx:
  configmap:
    enableunderscore: true
pod:
  initialDelaySeconds: 120
  timeoutSeconds: 60
replicaCount: 3
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 600m
    memory: 256Mi
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  externalPort: 5071
  internalPort: 5071
  name: hazelcast
  namespace: testhz
  type: ClusterIP

COMPUTED VALUES:
env:
  gitCommit: f34wew2a5aer33ffas7a
  springProfile: qa
image:
  pullPolicy: Always
  repository: hazelcast/hazelcast-kubernetes
  tag: 3.10-BETA-1
ingress:
  enabled: true
  hosts:
  - hazelcast.us-west-2.nonprod.cnqr.delivery
  tls:
  - hosts:
    - hazelcast.us-west-2.nonprod.cnqr.delivery
nginx:
  configmap:
    enableunderscore: true
pod:
  initialDelaySeconds: 120
  timeoutSeconds: 60
replicaCount: 3
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 600m
    memory: 256Mi
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  externalPort: 5071
  internalPort: 5071
  name: hazelcast
  namespace: testhz
  type: ClusterIP

HOOKS:
MANIFEST:

---
# Source: hazelcast-testhz/templates/nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hz-config
  namespace: testhz
data:
  HAZELCAST_KUBERNETES_NAMESPACE: testhz
  HAZELCAST_KUBERNETES_SERVICE_NAME: hazelcast
---
# Source: hazelcast-testhz/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: NodePort
  selector:
    app: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    name: hzport
---
# Source: hazelcast-testhz/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hazelcast
  namespace:  testhz
  labels:
    app: hazelcast
    chart: hazelcast-0.1.0
    release: hazelcast-hazelcast
    heritage: Tiller-hazelcast
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hazelcast
        release: hazelcast-hazelcast
    spec:
      containers:
        - name: hazelcast
          image: "hazelcast/hazelcast-kubernetes:3.10-BETA-1"
          imagePullPolicy: Always
          ports:
            - containerPort: 5071
          livenessProbe:
            exec:
              command:
              - "./liveness.sh"
            initialDelaySeconds: 120
            timeoutSeconds: 60
            periodSeconds: 10
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 600m
              memory: 256Mi
---
# Source: hazelcast-testhz/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hazelcast
  namespace: testhz
  labels:
    app: hazelcast
    chart: hazelcast-0.1.0
    release: hazelcast-hazelcast
    heritage: Tiller
  annotations:
spec:
  rules:
    - host: hazelcast.us-west-2.nonprod.cnqr.delivery
      http:
        paths:
          - path: /
            backend:
              serviceName: hazelcast
              servicePort: 5071
  tls:
    - hosts:
      - hazelcast.us-west-2.nonprod.cnqr.delivery
LAST DEPLOYED: Wed Feb 28 13:46:56 2018
NAMESPACE: testhz
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME       TYPE      CLUSTER-IP       EXTERNAL-IP  PORT(S)         AGE
hazelcast  NodePort  192.168.143.243  <none>       5701:31195/TCP  1s

==> v1beta1/Deployment
NAME       DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
hazelcast  3        3        3           0          1s

Kube logs

╰─ kcwizlog po/hazelcast-2366664114-202vc
Kubernetes Namespace: testhz
Kubernetes Service DNS:
########################################
# RUN_JAVA=
# JAVA_OPTS=
# CLASSPATH=/*:/opt/hazelcast/*:/opt/hazelcast/external/*:
########################################
Checking custom configuration
no custom configuration found
Feb 28, 2018 9:47:15 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Feb 28, 2018 9:47:15 PM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location is incorrect, using default
Feb 28, 2018 9:47:16 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.10-BETA-1] Prefer IPv4 stack is true.
Feb 28, 2018 9:47:16 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.10-BETA-1] Picked [172.16.18.169]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Feb 28, 2018 9:47:16 PM com.hazelcast.system
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Hazelcast 3.10-BETA-1 (20180221 - c9a445b) starting at [172.16.18.169]:5701
Feb 28, 2018 9:47:16 PM com.hazelcast.system
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
Feb 28, 2018 9:47:16 PM com.hazelcast.system
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Configured Hazelcast Serialization version: 1
Feb 28, 2018 9:47:16 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Backpressure is disabled
Feb 28, 2018 9:47:16 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-label: null, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc}
Feb 28, 2018 9:47:16 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Kubernetes Discovery: Bearer Token { eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3aXphcmRzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tbWx6NGoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk0MDNlNGJiLWMwZWEtMTFlNy05NTk4LTBhMGIxNzMwNDgwMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp3aXphcmRzOmRlZmF1bHQifQ.WBNhlfnXJ6_1d3KfVitj6L_tHXizIn-OgOpZV6DbZjataKWY37VlJBToSdJTvODlOh6V9LvI7C7bQl66DEpuhr3netv7Z0AFPFk1nlOvgblVwRDUqDNI5tTayD3sr5oIVRNNOqljPPa89UIYwCkL8BKxmZwMIE97r_tFRWEW01psU8U68UgE-2nudMHBkyRtRlKlRJsMkU79N9Y2Fbd1DqsNrTtenVyO9ZeTwLMw7cuhwvHl6N4wDjerJDM8VV4yjv5YUkrFD9ID0GINt6lXHCeTxcESkKxfvYVUxCAEKs2ixyMXIskwhI_fNvzetVzMfH95Fnu153amuwrvVtpqIA }
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 28, 2018 9:47:17 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Kubernetes Discovery activated resolver: ServiceEndpointResolver
Feb 28, 2018 9:47:17 PM com.hazelcast.instance.Node
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Activating Discovery SPI Joiner
Feb 28, 2018 9:47:17 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Starting 16 partition threads and 9 generic threads (1 dedicated for priority tasks)
Feb 28, 2018 9:47:17 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Feb 28, 2018 9:47:17 PM com.hazelcast.core.LifecycleService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] [172.16.18.169]:5701 is STARTING
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Connecting to /10.253.67.76:5701, timeout: 0, bind-any: true
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Connecting to /172.16.17.122:5701, timeout: 0, bind-any: true
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Connecting to /172.16.13.23:5701, timeout: 0, bind-any: true
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Connecting to /172.16.60.55:5701, timeout: 0, bind-any: true
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Could not connect to: /172.16.17.122:5701. Reason: SocketException[Connection refused to address /172.16.17.122:5701]
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Could not connect to: /172.16.13.23:5701. Reason: SocketException[Connection refused to address /172.16.13.23:5701]
Feb 28, 2018 9:47:18 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Could not connect to: /172.16.60.55:5701. Reason: SocketException[Connection refused to address /172.16.60.55:5701]
Feb 28, 2018 9:47:18 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] [172.16.17.122]:5701 is added to the blacklist.
Feb 28, 2018 9:47:18 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] [172.16.60.55]:5701 is added to the blacklist.
Feb 28, 2018 9:47:18 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] [172.16.13.23]:5701 is added to the blacklist.
Feb 28, 2018 9:47:23 PM com.hazelcast.system
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] Cluster version set to 3.10
Feb 28, 2018 9:47:23 PM com.hazelcast.internal.cluster.ClusterService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1]

Members {size:1, ver:1} [
	Member [172.16.18.169]:5701 - 1787f7b3-afbb-4dab-a375-c9d55f5ecbcf this
]

Feb 28, 2018 9:47:23 PM com.hazelcast.core.LifecycleService
INFO: [172.16.18.169]:5701 [dev] [3.10-BETA-1] [172.16.18.169]:5701 is STARTED

**Comment by vadimkim** [comment]
Look at your hazelcast.xml. It seems you didn't initialize the properties and that is why you have

> Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-label: null, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc}

at your logs

**Comment by googlielmo** [comment]
Closing this as original question was answered. Please feel free to open new issues if needed.
