### ISSUE TITLE
Is it working properly?

### ISSUE THREAD

**Issue by vadimkim** [hazelcast/hazelcast-kubernetes#66]
I think there should be more information about how this discovery plugin suppose to work inside Kubernetes. At the moment I can see the following logic:
1. Plugin queries either DNS or REST for Service endpoint (I have used DNS)
2. It gets Service IP + port 
3. Tries to establish connection with kubernetes service that randomly forwards query to backend hazelcast replicas in order to form the cluster
4. ???  fails actually, because service itself is ephemeral and is not a member of the cluster

Here are logs from one of the running pods inside minikube where I have tried to combine it with management server:

> $ kubectl logs hazelcast-server-d978ff479-vx4kk 
Kubernetes Namespace: default
Kubernetes Service DNS: 
'########################################
'# RUN_JAVA=
'# JAVA_OPTS=-Xms512M -Xmx2056M -Dcom.sun.management.jmxremote -'Dcom.sun.management.jmxremote.authenticate=false -Dhazelcast.diagnostics.enabled=true -'Dhazelcast.rest.enabled=true
'# CLASSPATH=/*:/opt/hazelcast/*:/opt/hazelcast/external/*:
'########################################
Checking custom configuration
no custom configuration found
Mar 06, 2018 6:47:52 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Mar 06, 2018 6:47:52 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.3] Prefer IPv4 stack is true.
Mar 06, 2018 6:47:52 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.3] Picked [172.17.0.7]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Mar 06, 2018 6:47:53 AM com.hazelcast.system
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Hazelcast 3.9.3 (20180216 - 539b124) starting at [172.17.0.7]:5701
Mar 06, 2018 6:47:53 AM com.hazelcast.system
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
Mar 06, 2018 6:47:53 AM com.hazelcast.system
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Configured Hazelcast Serialization version: 1
Mar 06, 2018 6:47:53 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Backpressure is disabled
Mar 06, 2018 6:47:53 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Kubernetes Discovery properties: { service-dns: hazelcast-service.default.svc.cluster.local, service-dns-timeout: 5, service-name: null, service-label: null, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc}
Mar 06, 2018 6:47:53 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Kubernetes Discovery activated resolver: DnsEndpointResolver
Mar 06, 2018 6:47:53 AM com.hazelcast.instance.Node
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Activating Discovery SPI Joiner
Mar 06, 2018 6:47:54 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Diagnostics started
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.BuildInfoPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.SystemPropertiesPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.ConfigPropertiesPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.MetricsPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.SlowOperationPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.SystemLogPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active: logPartitions:false
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active, period-millis:10000
Mar 06, 2018 6:47:54 AM com.hazelcast.internal.diagnostics.OperationHeartbeatPlugin
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Plugin:active: period-millis:10000 max-deviation:33%
Mar 06, 2018 6:47:54 AM com.hazelcast.core.LifecycleService
INFO: [172.17.0.7]:5701 [dev] [3.9.3] [172.17.0.7]:5701 is STARTING
Mar 06, 2018 6:47:54 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connecting to /10.99.49.133:5701, timeout: 0, bind-any: true
Mar 06, 2018 6:47:55 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Established socket connection between /172.17.0.7:44347 and /10.99.49.133:5701
Mar 06, 2018 6:47:55 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connection[id=1, /172.17.0.7:44347->/10.99.49.133:5701, **endpoint=[10.99.49.133]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side**
Mar 06, 2018 6:47:56 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connecting to /10.99.49.133:5701, timeout: 0, bind-any: true
Mar 06, 2018 6:47:57 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Established socket connection between /172.17.0.7:51935 and /10.99.49.133:5701
Mar 06, 2018 6:47:57 AM com.hazelcast.nio.tcp.TcpIpConnection
**INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connection[id=2, /172.17.0.7:51935->/10.99.49.133:5701, endpoint=[10.99.49.133]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side**
Mar 06, 2018 6:47:58 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connecting to /10.99.49.133:5701, timeout: 0, bind-any: true
Mar 06, 2018 6:47:59 AM com.hazelcast.system
INFO: [172.17.0.7]:5701 [dev] [3.9.3] Cluster version set to 3.9
Mar 06, 2018 6:47:59 AM com.hazelcast.internal.cluster.ClusterService
INFO: [172.17.0.7]:5701 [dev] [3.9.3] 

> 
> Members {size:1, ver:1} [
> 	Member [172.17.0.7]:5701 - 1cded4bf-6f7b-4bf8-92cc-c11645db87dc this
> ]
> 
> Mar 06, 2018 6:47:59 AM com.hazelcast.internal.management.ManagementCenterService
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] Hazelcast will connect to Hazelcast Management Center on address: 
> http://localhost:8080/mancenter
> Mar 06, 2018 6:47:59 AM com.hazelcast.core.LifecycleService
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] [172.17.0.7]:5701 is STARTED
> Mar 06, 2018 6:47:59 AM com.hazelcast.internal.management.ManagementCenterService
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] Failed to pull tasks from management center
> Mar 06, 2018 6:47:59 AM com.hazelcast.internal.management.ManagementCenterService
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] Failed to connect to:http://localhost:8080/mancenter/collector.do
> Mar 06, 2018 6:48:01 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] Established socket connection between /172.17.0.7:60675 and /10.99.49.133:5701
> Mar 06, 2018 6:48:01 AM com.hazelcast.nio.tcp.TcpIpConnection
> INFO: [172.17.0.7]:5701 [dev] [3.9.3] Connection[id=3, /172.17.0.7:60675->/10.99.49.133:5701, **endpoint=[10.99.49.133]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side**
>

**Comment by googlielmo** [comment]
Hi @vadimkim thank you for reporting this.
Can you try using service endpoint REST API instead? I believe it should give you the correct address for the Hazelcast members.
DNS is mostly useful in some very specific scenario, e.g. Openshift.
We will provide more documentation going forward.

**Comment by vadimkim** [comment]
Thank you @googlielmo. With REST api it works much better. I have also added overlay kubernetes network and now all hosts are able to discover each other:

```
Kubernetes Namespace: default
Kubernetes Service DNS: 
'########################################
'# RUN_JAVA=
'# JAVA_OPTS=-Xms512M -Xmx2056M -Dcom.sun.management.jmxremote -'Dcom.sun.management.jmxremote.authenticate=false -Dhazelcast.diagnostics.enabled=true -'Dhazelcast.rest.enabled=true
'# CLASSPATH=/*:/opt/hazelcast/*:/opt/hazelcast/external/*:
'########################################
Checking custom configuration
no custom configuration found
Mar 07, 2018 12:10:58 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Mar 07, 2018 12:10:59 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.3] Prefer IPv4 stack is true.
Mar 07, 2018 12:10:59 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.9.3] Picked [10.1.0.28]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Mar 07, 2018 12:10:59 PM com.hazelcast.system
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Hazelcast 3.9.3 (20180216 - 539b124) starting at [10.1.0.28]:5701
Mar 07, 2018 12:10:59 PM com.hazelcast.system
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
Mar 07, 2018 12:10:59 PM com.hazelcast.system
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Configured Hazelcast Serialization version: 1
Mar 07, 2018 12:10:59 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Backpressure is disabled
Mar 07, 2018 12:11:00 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: hazelcast-service, service-label: cluster01, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc}
Mar 07, 2018 12:11:00 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Kubernetes Discovery: Bearer Token { eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tanNyZnciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijg3MzM1M2U4LTFjN2UtMTFlOC1iZDVkLTA4MDAyN2UzYmVkNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.DUQzKVwajGjwjcFGvsCVwyPcJ_YPt_KKygodQUwOzT0IH2wOT86l_sX8mrBoVQF1yrpZ5if2iUWKiEsntm6uivaktaM35pZkj5pDSaSPeAEZsHuOUkPtqE4u4kACFAd90KKQdu_Rcn6HFSi5fQjRJo1lVATCV98HHEeMNbEgc8nZPFXDevwQaZOtyanNU560KJyusftJNJsQu4MS0dXTY687hx42x6nvuoXQim8tI1KzubIVjNeWcLHYYufldyBEzwO3TmkZBSraeALCFqYzCgJabvFZji450vmQwH5m6v1DxXuE0OljuJzs1WX_F9XDqkOidzcL-DWa7kmNe6SnRA }
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 07, 2018 12:11:00 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Kubernetes Discovery activated resolver: ServiceEndpointResolver
Mar 07, 2018 12:11:01 PM com.hazelcast.instance.Node
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Activating Discovery SPI Joiner
Mar 07, 2018 12:11:01 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Diagnostics started
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.BuildInfoPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.SystemPropertiesPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.ConfigPropertiesPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.MetricsPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.SlowOperationPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active, period-millis:60000
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.SystemLogPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active: logPartitions:false
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active, period-millis:10000
Mar 07, 2018 12:11:01 PM com.hazelcast.internal.diagnostics.OperationHeartbeatPlugin
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Plugin:active: period-millis:10000 max-deviation:33%
Mar 07, 2018 12:11:01 PM com.hazelcast.core.LifecycleService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] [10.1.0.28]:5701 is STARTING
Mar 07, 2018 12:11:02 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Connecting to /10.1.0.27:5701, timeout: 0, bind-any: true
Mar 07, 2018 12:11:02 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Established socket connection between /10.1.0.28:39055 and /10.1.0.27:5701
Mar 07, 2018 12:11:13 PM com.hazelcast.system
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Cluster version set to 3.9
Mar 07, 2018 12:11:13 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] 

Members {size:2, ver:2} [
	Member [10.1.0.27]:5701 - 379a99b4-c9d7-49e9-ad2c-688add1ad151
	Member [10.1.0.28]:5701 - 46fabb0a-7774-469a-98a0-6e6eabd56459 this
]

Mar 07, 2018 12:11:15 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Failed to pull tasks from management center
Mar 07, 2018 12:11:15 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Hazelcast will connect to Hazelcast Management Center on address: 
http://localhost:8080/mancenter
Mar 07, 2018 12:11:15 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] Failed to connect to:http://localhost:8080/mancenter/collector.do
Mar 07, 2018 12:11:16 PM com.hazelcast.core.LifecycleService
INFO: [10.1.0.28]:5701 [dev] [3.9.3] [10.1.0.28]:5701 is STARTED

```
