### ISSUE TITLE
Nodes/Instances are registered more than once

### ISSUE THREAD

**Issue by codeCoder** [hazelcast/hazelcast-kubernetes#73]
Hi,

i build a small spring boot app (https://github.com/codeCoder/spring-boot-hello-world)
 to get involved with kubernetes and hazelcast in it.

During the start it looks like a single hazelcast instance is registered more than once in the cluster with different ports. In https://github.com/codeCoder/spring-boot-hello-world/blob/master/hello_world_last_run_first_pod 
you see following lines

> Members {size:3, ver:3} [
	Member [172.17.0.8]:5701 - 96d9f638-9a22-4305-a68c-4e222b10e4aa this
	Member [172.17.0.8]:5702 - 065b6ec2-3996-4230-a186-ebc4e5d6a3a5
	Member [172.17.0.8]:5703 - b087dfc0-bd6b-4e9e-b0a7-44dd324e8034
]

If i start a second pod(see: https://github.com/codeCoder/spring-boot-hello-world/blob/master/hello_world_last_run_second_pod)

you see much more nodes/ instances registered in the cluster:
> Members {size:6, ver:6} [
	Member [172.17.0.8]:5701 - 96d9f638-9a22-4305-a68c-4e222b10e4aa
	Member [172.17.0.8]:5702 - 065b6ec2-3996-4230-a186-ebc4e5d6a3a5
	Member [172.17.0.8]:5703 - b087dfc0-bd6b-4e9e-b0a7-44dd324e8034
	Member [172.17.0.11]:5701 - a8bc9171-e10f-4c26-9ad6-1a6fc43446ce
	Member [172.17.0.11]:5702 - 1669f5a6-1fa5-442b-9745-c2e7a014be03 this
	Member [172.17.0.11]:5703 - c41ac3df-f2d1-4ef7-88ca-8cf0afd78b54
]

At the moment I use this rest config: https://github.com/codeCoder/spring-boot-hello-world/blob/master/src/main/resources/hazelcast-kubernetes-restapi.xml

with following network settings:
> <network>
        <port>5701</port>
        <join>
            
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            
            <discovery-strategies>
                <discovery-strategy enabled="true"
                                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                    <properties>
                        
                        <property name="service-name">spring-boot-hello-world-service-cluster</property>
                        <property name="service-label-name">run</property>
                        <property name="service-label-value">spring-boot-hello-world-service-cluster</property>
                        <property name="namespace">default</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>

I still have to test if the cache is working properly. But first I would like to understand this behavior.

**Comment by leszko** [comment]
@codeCoder , do you use a separate service for each cluster? If you use "spring-boot-hello-world-service-cluster" for both, then all six nodes would join the same cluster.

**Comment by codeCoder** [comment]
@leszko Sorry i don't think i understand your question. But my idea is to connect all https://github.com/codeCoder/spring-boot-hello-world/blob/master/src/k8s/02-deployment.yaml
spring-boot-instances (at the beginning there is only one) via the service https://github.com/codeCoder/spring-boot-hello-world/blob/master/src/k8s/01-service-hz-cluster.yaml
to share a distributed hz cache. The name of this service is in the hazelcast.xml. Btw. i test this yaml configs in my own minikube instance. There is only one node avail. I just scale up to 2 instances and get the output you can see above in the first comment. 
The second service https://github.com/codeCoder/spring-boot-hello-world/blob/master/src/k8s/03-service-hz-application-service.yaml is irrelevant for this scenario.

**Comment by leszko** [comment]
@codeCoder , sorry I misunderstood you question.

Actually, you're right, your application creates 3 Hazelcast instances, however the reason for that is not related to Kubernetes, but to your Spring configuration. Change your last two beans declaration to the following and it will work fine.

```
    @Bean
    public CacheManager cacheManager(HazelcastInstance hazelcastInstance) {
        return new HazelcastCacheManager(hazelcastInstance);
    }

    @Bean
    public Cache dateCache(HazelcastInstance hazelcastInstance) {
        return cacheManager(hazelcastInstance).getCache("dateCache");
    }
```

**Comment by codeCoder** [comment]
@leszko It works!
Cool! I have now a good example how to implement rest api based discovery of hz nodes in k8s cluster!

Thanks a lot.

Do you have a working example of the dns method?

**Comment by leszko** [comment]
@codeCoder I don't think we have a complete example, the best you can do is to read [1] and [2]. If the nodes don't see each other, check that you defined the "service-dns" env variable correctly (read more [3]).

[1] https://github.com/hazelcast/hazelcast-kubernetes#dns-lookup
[2] https://github.com/hazelcast/hazelcast-docker/tree/master/hazelcast-kubernetes
[3] https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by topikachu** [comment]
@codeCoder, You need to create a headless service and use this as the DNS name.

**Comment by codeCoder** [comment]
@topikachu 
Can you provide some code? I don't understand what you mean.

**Comment by codeCoder** [comment]
I got it. I created following service config. Now it works.
`# headless service
# for more info see: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
apiVersion: v1
kind: Service
metadata:
  labels:
    run: spring-boot-hello-world-service-cluster
  name: spring-boot-hello-world-service-cluster
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5701
      targetPort: 5701
      name: hazelcast
  selector:
    app: spring-boot-hello-world`
