### ISSUE TITLE
Revise readme

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-kubernetes#74]
The main readme of this project could get some love. It talks too much about implementation details and too little about actual usage. 

Example - this is close to the top of the readme:
![image](https://user-images.githubusercontent.com/158619/40830168-f72143a6-6585-11e8-8431-95d7ce2b9b4c.png)

While this is at the bottom:
![image](https://user-images.githubusercontent.com/158619/40830182-0493f416-6586-11e8-80e5-0a15efeef91a.png)

The SPI is purely an implementation detail, while I reckon majority of users are interested in the Docker images. 

In general the readme should be more use-case oriented.

**Comment by bitvector2** [comment]
Nobody is interested in docker images IMHO - they are interested in using Hazelcast embedded in their own microservices.
