### ISSUE TITLE
PROPERTY_DEFINITIONS is missing SERVICE_DNS_TIMEOUT in HazelcastKubernetesDiscoveryStrategyFactory.java

### ISSUE THREAD

**Issue by bitvector2** [hazelcast/hazelcast-kubernetes#76]
Right after [this line](https://github.com/hazelcast/hazelcast-kubernetes/blob/f2c7d1c24802c0c12f66e6d4ed23367f6debf490/src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java#L40) is where the property should be declared...

**Comment by leszko** [comment]
Thanks @bitvector2 for spotting that! Could I ask you to send a PR with the fix?
