### ISSUE TITLE
Enable external Smart Client (expose PODs and assign public IP automatically using Kubernetes API)

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#77]
Currently, if someone deploys a Hazelcast cluster (manually or via Helm Chart), it's accessible via `LoadBalancer` service and therefore available only with the use of Dummy Client. That is the standard way how Kubernetes deals with multiple PODs. They are accessible only via one service [1].

It should be possible to expose each POD separately (using the Kubernetes Adds-On "Service Per POD" [2]). Then, we could use Kubernetes API to get the information about external IPs and set it in `discoverNodes()` or `AddressPicker` implementation.

[1] https://stackoverflow.com/questions/45650526/kubernetes-expose-only-single-pod-of-statefulset
[2] https://github.com/GoogleCloudPlatform/metacontroller/tree/master/examples/service-per-pod

**Comment by alexsergin** [comment]
And there is a problem to discover pods between multiple kubernetes clusters. So in this way I'll need to manually add hz cluster members
