### ISSUE TITLE
Project Dependecies

### ISSUE THREAD

**Issue by ade90036** [hazelcast/hazelcast-kubernetes#87]
Hi,

I have been using your plugin with great success. 👍 
I had less luck in configuring the plugin to use the kubernetes api due to RBAC user permission on the service. However the DNS lookup worked flawlessly and i don't need to anything.

I'm using this version (gradle)
```
compile group: 'com.hazelcast', name: 'hazelcast-kubernetes', version: '1.1.0'
```
When gradle resolved the dependecies it also pulls in this:

```
//https://mvnrepository.com/artifact/com.hazelcast/hazelcast-kubernetes/1.1.0
io.fabric8:kubernetes-client:3.0.3
```

Looking at the project, this is not used anymore.

Would it be possible to get a new build with this dependency removed?

Regards

ade

**Comment by ade90036** [comment]
Excellent, thanks for the prompt reply.

**Comment by leszko** [comment]
@ade90036 , FYI: `hazelcast-kubernetes 1.2` is released.
