### ISSUE TITLE
Hazelcast starts in Standalone mode in 3.9.2

### ISSUE THREAD

**Issue by Gephorian** [hazelcast/hazelcast-kubernetes#88]
In the example XML you have

```
<!-- only necessary prior Hazelcast 3.8 -->
<property name="hazelcast.discovery.enabled">true</property>
```

This is misleading, we needed to have the property in 3.9 as well. Without it, we'd get a log message saying "No join methods enabled, starting in standalone mode." and the cluster would fail to initialize.

**Comment by leszko** [comment]
Thanks @Gephorian for pointing that out!
