### ISSUE TITLE
Write Blog Post about using Kubernetes

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#90]
Write a Blog Post or a series of blog posts about:
- Using Kubernetes plugin
  - with DNS Lookup Discovery
  - with REST API Discovery
- Using Hazelcast Helm Chart

Kubernetes [1] and OpenShift [2] code samples can be used.

[1] https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes
[2] https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift

**Comment by leszko** [comment]
Neil added a Blog Post on K8. I added a Post on Helm Chart. Closing.

**Comment by mesutcelik** [comment]
Those are the mentioned blog post links as a reference.
https://blog.hazelcast.com/hazelcast-helm-chart/
https://blog.hazelcast.com/hazelcast-on-kubernetes-made-fairly-easy/
