### ISSUE TITLE
Make Kubernetes ZONE_AWARE

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#92]
Use the label value of `failure-domain.beta.kubernetes.io/zone` to retrieve the zone and make Hazelcast Zone Aware.

The label can be retrieved as follows from Kubernetes Master:
1. Get `nodeName` from `/api/v1/namespaces/<namespace>/endpoints`
2. Get label value from `/api/v1/nodes/<nodeName>`

Note that the RBAC sample yaml (+ Helm Charts) need to be adapted to give read access to the `/nodes` endpoint.

**Comment by jerrinot** [comment]
@leszko: isnt this fixed by https://github.com/hazelcast/hazelcast-kubernetes/pull/122 ?

**Comment by leszko** [comment]
Yes, sorry I forgot to close this one.

Fixed by #122
